apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-network-checking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-network-checking
  template:
    metadata:
      labels:
        app: k8s-network-checking
    spec:
      containers:
      - name: k8s-network-checking
        image: nrt.ocir.io/sehubjapacprod/k8s-network-checking
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-network-checking-service
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
spec:
  selector:
    app: k8s-network-checking
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080